#!/usr/bin/env python3
"""Fetch pinned wand125 generated sources without replacing local changes.

Examples (no Lean process is run):
  python3 scripts/fetch_wand125_release.py --unit U2G --case 220 --list
  python3 scripts/fetch_wand125_release.py --unit F --field 1 --from-dir /path/to/assets

The default destination is .verification/wand125/staged, containing Sqpack/.
Use --destination . explicitly to materialize into the current checkout. Every
selected archive and source is verified before any destination file is created.
Existing identical files are retained; differing files and symlinks are errors.
The cache retains verified archives. No downloaded checksum file is trusted.
The auxiliary F00/Roots.txt is also verified but only .lean files are installed.
"""
import argparse
import errno
import hashlib
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import ssl
import sys
import tarfile
import tempfile
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
METADATA = ROOT / "integrations/wand125/release"
PINNED_REF = "a8b51d3e0682beb1bf911048bdc8e7fa62329124"
RELEASE_URL = "https://github.com/wand125/n11-optimality-lean/releases/download/n11-certs-v1"
# Exact git blobs at PINNED_REF, scripts/field/ or scripts/u2p/.
METADATA_HASHES = {
    "MANIFEST_F.sha256": "254d751b836bcb054082db48cd48c8faa93b7ebb514516d1d37509bcaae1b8c6",
    "MANIFEST_FCOMMON.sha256": "0eb70d6356c45417cc76731025ea2792dd04d08ee9261ea7271d572240c15dbf",
    "MANIFEST_U2G.sha256": "430000e44957cb5b34ed66e74a46ae24fc8b6375889a1a215a61d0f094fb4e0d",
    "MANIFEST_U2P.sha256": "1b92c090e932996629857fa01864d529e402f1e80f3fbc158b4f74b4c43bec05",
    "MANIFEST_U2R.sha256": "81a219885c34bf3c60628327b14184fb554894c8d3069f6a6076245604811399",
    "SHA256SUMS_F": "34d73bc166043c1ff952c910c804fdaf17f1355f5ca02e0438a170d765c952c7",
    "SHA256SUMS_U2G": "802567f6261cf6bc8317e19d5588c6e9f973974291489f5e182003229974438a",
    "SHA256SUMS_U2P": "4454ee9d17551a72d6671ceac789086343a3dc8c97c20a95b55c4dad59390f27",
    "SHA256SUMS_U2R": "c570a9de322f254a11a13f2614525f8beb713c71d873b7aa5b618793bf7166af",
    # U5 (case438 extended traces) is generated by scripts/wand125_u5/ of this repository.
    "MANIFEST_U5.sha256": "d847f85960c826204adb6d7d9fa3962d1471960712c6449108e59bbf0dd25642",
    "SHA256SUMS_U5": "6e7134ac089a1f12948be5144e506192f53eef7c1253ab8acfe91434eda5a6eb",
}
# U5 nodes: one archive n11-u5-<node>.tar.xz each, under ElevenSquare/Tasks/T07/Ext/Gen.
U5_NODES = ("P2", "Root240", "Far15", "R1", "R10", "Far13", "Near13", "R11", "R110", "R111", "Near")
MIB = 1024 * 1024
RESERVE = 64 * MIB


class ReleaseError(ValueError):
    """Input or filesystem state does not satisfy the release contract."""


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as source:
        for block in iter(lambda: source.read(MIB), b""):
            h.update(block)
    return h.hexdigest()


def safe_name(name):
    """Accept canonical relative POSIX paths, never normalize traversal away."""
    if (not name or "\\" in name or "\x00" in name or name.startswith("/")
            or any(part in ("", ".", "..") for part in name.split("/"))):
        raise ReleaseError(f"unsafe path: {name!r}")
    return name


def read_hashes(path, expected_hash=None):
    if path.is_symlink() or not path.is_file():
        raise ReleaseError(f"not a regular metadata file: {path}")
    if expected_hash and sha256_file(path) != expected_hash:
        raise ReleaseError(f"pinned metadata hash mismatch: {path.name}")
    result = {}
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip() or line.startswith("#"):
            continue
        match = re.fullmatch(r"([0-9a-f]{64})  (\S+)", line)
        if not match:
            raise ReleaseError(f"invalid hash entry: {path.name}:{number}")
        digest, name = match.groups()
        safe_name(name)
        if name in result:
            raise ReleaseError(f"duplicate hash entry: {name}")
        result[name] = digest
    if not result:
        raise ReleaseError(f"empty manifest: {path}")
    return result


def release_plan(unit, cases=None):
    """Return [(archive filename, archive digest, {full source path: digest})]."""
    manifest_name = f"MANIFEST_{unit}.sha256"
    sums_name = f"SHA256SUMS_{'F' if unit == 'FCOMMON' else unit}"
    manifest = read_hashes(METADATA / manifest_name, METADATA_HASHES[manifest_name])
    sums = read_hashes(METADATA / sums_name, METADATA_HASHES[sums_name])
    if unit == "U5":
        return u5_plan(manifest, sums, cases)
    parent = "Sqpack/S11Opt" if unit in ("F", "FCOMMON") else f"Sqpack/S11Opt/Split/{unit}"
    groups = {}
    for relative, digest in manifest.items():
        parts = relative.split("/")
        auxiliary = unit == "F" and relative == "F00/Roots.txt"
        if (not relative.endswith(".lean") and not auxiliary) or len(parts) > 2:
            raise ReleaseError(f"unexpected manifest path: {relative}")
        if unit == "FCOMMON":
            key = None
        else:
            prefix = "F" if unit == "F" else "C"
            if len(parts) != 2 or not re.fullmatch(prefix + r"[0-9]+", parts[0]):
                raise ReleaseError(f"unexpected case directory: {relative}")
            key = int(parts[0][1:])
            canonical = f"F{key:02d}" if unit == "F" else f"C{key}"
            if parts[0] != canonical:
                raise ReleaseError(f"noncanonical case directory: {relative}")
        groups.setdefault(key, {})[f"{parent}/{relative}"] = digest
    if unit == "FCOMMON" and cases is not None:
        raise ReleaseError("FCOMMON has no case/field selector")
    selected = sorted(groups) if cases is None else sorted(set(cases))
    plan = []
    for case in selected:
        if case not in groups:
            raise ReleaseError(f"{unit} case {case} is absent from the pinned manifest")
        if unit == "FCOMMON":
            asset = "n11-field-common.tar.xz"
        elif unit == "F":
            asset = f"n11-field-F{case:02d}.tar.xz"
        else:
            asset = f"n11-{unit.lower()}-C{case:04d}.tar.xz"
        if asset not in sums:
            raise ReleaseError(f"archive absent from pinned checksums: {asset}")
        plan.append((asset, sums[asset], groups[case]))
    return plan


def u5_plan(manifest, sums, cases):
    """U5 groups by node: `<node>/<file>.lean`, `<node>.lean`, and `NearConn.lean` (node Near)."""
    if cases is not None:
        raise ReleaseError("U5 has no case selector")
    groups = {}
    for relative, digest in manifest.items():
        parts = relative.split("/")
        if not relative.endswith(".lean") or len(parts) > 2:
            raise ReleaseError(f"unexpected manifest path: {relative}")
        node = "Near" if relative == "NearConn.lean" else parts[0].removesuffix(".lean")
        if node not in U5_NODES:
            raise ReleaseError(f"unexpected U5 node: {relative}")
        groups.setdefault(node, {})[f"ElevenSquare/Tasks/T07/Ext/Gen/{relative}"] = digest
    plan = []
    for node in U5_NODES:
        asset = f"n11-u5-{node.lower()}.tar.xz"
        if node not in groups:
            raise ReleaseError(f"U5 node {node} is absent from the pinned manifest")
        if asset not in sums:
            raise ReleaseError(f"archive absent from pinned checksums: {asset}")
        plan.append((asset, sums[asset], groups[node]))
    return plan


def require_space(path, needed):
    """Check the filesystem of the nearest existing parent, with a reserve."""
    path = Path(path)
    while not path.exists():
        path = path.parent
    if shutil.disk_usage(path).free < needed + RESERVE:
        raise ReleaseError(f"insufficient disk space at {path}: need {needed + RESERVE} bytes")


def checked_archive(path, digest, limit):
    if path.is_symlink() or not path.is_file():
        raise ReleaseError(f"not a regular archive: {path}")
    if path.stat().st_size > limit:
        raise ReleaseError(f"archive size limit exceeded: {path.name}")
    if sha256_file(path) != digest:
        raise ReleaseError(f"archive sha256 mismatch: {path.name}")


def cache_archive(asset, digest, cache, from_dir, limit):
    target = cache / asset
    if target.exists() or target.is_symlink():
        checked_archive(target, digest, limit)
        return target
    local = from_dir / asset if from_dir is not None else None
    if local is not None:
        checked_archive(local, digest, limit)
        required = local.stat().st_size
    else:
        required = limit  # Bound even a response without Content-Length.
    require_space(cache, required)
    cache.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{asset}.", dir=cache)
    temporary = Path(temporary)
    try:
        with os.fdopen(fd, "wb") as output:
            if local is not None:
                source = open(local, "rb")
            else:
                # macOS's standalone Python may lack bundled CA roots. Use the
                # system trust bundle when present; certificate checking stays on.
                system_ca = Path("/etc/ssl/cert.pem")
                context = ssl.create_default_context(cafile=str(system_ca) if system_ca.is_file() else None)
                source = urllib.request.urlopen(f"{RELEASE_URL}/{asset}", timeout=60, context=context)
            with source:
                if local is None:
                    length = source.headers.get("Content-Length")
                    if length is not None and int(length) > limit:
                        raise ReleaseError(f"archive size limit exceeded: {asset}")
                size = 0
                while block := source.read(MIB):
                    size += len(block)
                    if size > limit:
                        raise ReleaseError(f"archive size limit exceeded: {asset}")
                    output.write(block)
        checked_archive(temporary, digest, limit)
        try:
            os.link(temporary, target)  # Do not overwrite a concurrently created cache entry.
        except FileExistsError:
            checked_archive(target, digest, limit)
        return target
    finally:
        temporary.unlink(missing_ok=True)


def inspect_archive(archive, want, limit):
    """Validate all members and declared sizes before extracting anything."""
    allowed_dirs = {str(parent) for name in want for parent in PurePosixPath(name).parents
                    if str(parent) != "."}
    seen, files, total = set(), {}, 0
    with tarfile.open(archive, "r:xz") as bundle:
        for member in bundle:
            name = member.name
            if name.startswith("./"):
                name = name[2:]
            if member.isdir():
                name = name.removesuffix("/")
            safe_name(name)
            if name in seen:
                raise ReleaseError(f"duplicate archive member: {name}")
            seen.add(name)
            if member.isdir() and name in allowed_dirs and member.size == 0:
                continue
            if (not member.isreg() or member.issparse() or name not in want
                    or member.size < 0):
                raise ReleaseError(f"unexpected archive member: {member.name}")
            total += member.size
            if total > limit:
                raise ReleaseError("extracted size limit exceeded")
            files[name] = member
    missing = set(want) - set(files)
    if missing:
        raise ReleaseError(f"archive missing manifest files: {sorted(missing)[:3]}")
    return files, total


def extract_verified(archive, files, want, stage):
    with tarfile.open(archive, "r:xz") as bundle:
        for name, member in files.items():
            target = stage / name
            target.parent.mkdir(parents=True, exist_ok=True)
            with bundle.extractfile(member) as source, target.open("xb") as output:
                shutil.copyfileobj(source, output, MIB)
            if target.stat().st_size != member.size or sha256_file(target) != want[name]:
                raise ReleaseError(f"source sha256 mismatch: {name}")


def check_target(destination, name, digest):
    target = destination / name
    for parent in target.parents:
        if parent == destination.parent:
            break
        if parent.is_symlink() or (parent.exists() and not parent.is_dir()):
            raise ReleaseError(f"unsafe destination directory: {parent}")
    if target.is_symlink():
        raise ReleaseError(f"destination is a symlink: {target}")
    if target.exists():
        if not target.is_file() or sha256_file(target) != digest:
            raise ReleaseError(f"existing destination differs: {target}")
        return False
    return True


def materialize(stage, destination, want):
    """Preflight every collision, then install without replacing any file."""
    pending = [name for name, digest in want.items() if check_target(destination, name, digest)]
    require_space(destination, sum((stage / name).stat().st_size for name in pending))
    created, directories = [], []
    try:
        for name in pending:
            if not check_target(destination, name, want[name]):
                continue
            target = destination / name
            missing = []
            parent = target.parent
            while not parent.exists():
                missing.append(parent)
                parent = parent.parent
            for directory in reversed(missing):
                directory.mkdir()
                directories.append(directory)
            try:
                os.link(stage / name, target)
                created.append(target)
            except OSError as error:
                if error.errno == errno.EEXIST:
                    check_target(destination, name, want[name])
                elif error.errno == errno.EXDEV:
                    with target.open("xb") as output:
                        created.append(target)
                        with (stage / name).open("rb") as source:
                            shutil.copyfileobj(source, output, MIB)
                else:
                    raise
    except Exception:
        for path in reversed(created):
            path.unlink()
        for path in reversed(directories):
            path.rmdir()
        raise
    return len(created)


def fetch_release(plan, cache, destination, from_dir=None,
                  max_archive=1024 * MIB, max_extracted=4096 * MIB):
    """Cache, inspect, stage, and verify the complete selection before installing."""
    if Path(destination).is_symlink():
        raise ReleaseError(f"destination root is a symlink: {destination}")
    cache, destination = Path(cache).resolve(), Path(destination).resolve()
    from_dir = Path(from_dir).resolve() if from_dir is not None else None
    inspected, want, total = [], {}, 0
    for asset, digest, expected in plan:
        if set(expected) & set(want):
            raise ReleaseError("overlapping source paths in release selection")
        archive = cache_archive(asset, digest, cache, from_dir, max_archive)
        members, size = inspect_archive(archive, expected, max_extracted - total)
        total += size
        want.update(expected)
        inspected.append((archive, members, expected))
    require_space(cache, total)
    cache.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".stage-", dir=cache) as temporary:
        stage = Path(temporary)
        for archive, members, expected in inspected:
            extract_verified(archive, members, expected, stage)
        sources = {name: digest for name, digest in want.items() if name.endswith(".lean")}
        count = materialize(stage, destination, sources)
    return count, len(sources)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--unit", required=True, type=str.upper, choices=("F", "FCOMMON", "U2G", "U2P", "U2R", "U5"))
    parser.add_argument("--case", "--field", dest="cases", type=int, action="append",
                        help="select one case/field; repeat for several (default: whole unit)")
    parser.add_argument("--cache-dir", type=Path, default=ROOT / ".verification/wand125/releases")
    parser.add_argument("--destination", type=Path, default=ROOT / ".verification/wand125/staged",
                        help="destination root containing Sqpack/; default is an ignored staging tree")
    parser.add_argument("--from-dir", type=Path, help="copy archives from a local directory without network access")
    parser.add_argument("--max-archive-mib", type=int, default=1024, help="limit per compressed archive (default: 1024)")
    parser.add_argument("--max-extracted-mib", type=int, default=4096, help="limit for all selected extracted files (default: 4096)")
    parser.add_argument("--list", action="store_true", help="validate pinned metadata and list selection without downloading")
    args = parser.parse_args(argv)
    try:
        if args.max_archive_mib <= 0 or args.max_extracted_mib <= 0:
            raise ReleaseError("size limits must be positive")
        plan = release_plan(args.unit, args.cases)
        if args.list:
            for asset, digest, want in plan:
                print(f"{asset}  {digest}  {len(want)} manifest files")
            return 0
        created, total = fetch_release(plan, args.cache_dir, args.destination, args.from_dir,
                                       args.max_archive_mib * MIB, args.max_extracted_mib * MIB)
        print(f"Verified {total} sources; created {created}, retained {total - created} identical files in {args.destination}")
        return 0
    except (OSError, ValueError, tarfile.TarError) as error:
        print(f"Release fetch failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
